version: "2"
services:
  app:
    image: "node:8"
    user: "node"
    build: .
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    expose:
      - "8081"
    command: "npm start"
